// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ1P2oX9hgGC9aJm5UYhWeTwlVDaZwDeU',
    appId: '1:797825811436:web:b923c5e014466c389bf6c9',
    messagingSenderId: '797825811436',
    projectId: 'crashdetection-61614',
    authDomain: 'crashdetection-61614.firebaseapp.com',
    storageBucket: 'crashdetection-61614.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSIgbe01iBmemoZcdljhxsLQ1_UEhxHUY',
    appId: '1:797825811436:android:093d72a2cbba1b6e9bf6c9',
    messagingSenderId: '797825811436',
    projectId: 'crashdetection-61614',
    storageBucket: 'crashdetection-61614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbQ2EIdY2gmhmg9L3S9c1u6C1deMBERu8',
    appId: '1:797825811436:ios:c3c019b4c0286e159bf6c9',
    messagingSenderId: '797825811436',
    projectId: 'crashdetection-61614',
    storageBucket: 'crashdetection-61614.appspot.com',
    iosClientId: '797825811436-fll3mh1uml5nse95938s7lelkv9ka75n.apps.googleusercontent.com',
    iosBundleId: 'com.example.collisionDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbQ2EIdY2gmhmg9L3S9c1u6C1deMBERu8',
    appId: '1:797825811436:ios:c80d2a5930dde7119bf6c9',
    messagingSenderId: '797825811436',
    projectId: 'crashdetection-61614',
    storageBucket: 'crashdetection-61614.appspot.com',
    iosClientId: '797825811436-0vc01j6qa3fj76tme4prmi8upbtip4lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.collisionDetection.RunnerTests',
  );
}
